In [1]:
import numpy

In [2]:
import numpy as np

# Question 1

In [3]:
arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

In [7]:
l1 = []
l2 = []

for i in range(5):
  x=int(input("Enter the value for l1 : "))
  l1.append(x)

for i in range(5):
  x=int(input("Enter the value for l2 : "))
  l2.append(x)

arr1 = np.array(l1)
arr2 = np.array(l2)

print(arr1)
print(arr2)

arr = np.concatenate((arr1, arr2))
print("Array value for concatenated arr :",arr)

Sorted_Array = np.sort(arr)
print("Sorted Array for concatenated arr :",Sorted_Array)

Enter the value for l1 : 3
Enter the value for l1 : 44
Enter the value for l1 : 32
Enter the value for l1 : 6
Enter the value for l1 : 44
Enter the value for l2 : 67
Enter the value for l2 : 5
Enter the value for l2 : 8
Enter the value for l2 : 9
Enter the value for l2 : 43
[ 3 44 32  6 44]
[67  5  8  9 43]
Array value for concatenated arr : [ 3 44 32  6 44 67  5  8  9 43]
Sorted Array for concatenated arr : [ 3  5  6  8  9 32 43 44 44 67]


# Question 3

In [8]:
arr = np.array([[1,2,3],[3,4,6],[5,6,8]])
arr

array([[1, 2, 3],
       [3, 4, 6],
       [5, 6, 8]])

In [10]:
#size of array

print(arr.size)

9


In [11]:
#dimension of array

print(arr.ndim)

2


# Question 4

In [ ]:
arr = np.arange(6)

# Question 5

In [6]:
import numpy
import numpy as np
#Let two arrays be
arr1 = np.square([ 1,2,3,4,5,6 ])
arr2 = np.square([ 8,7,6,5,4,3 ])

#Stacking
print("stacked horizontally:",np.hstack((arr1, arr2)))
print("Stacked vertically:",np.vstack((arr1,arr2)))

stacked horizontally: [ 1  4  9 16 25 36 64 49 36 25 16  9]
Stacked vertically: [[ 1  4  9 16 25 36]
 [64 49 36 25 16  9]]


# Question 6

In [21]:
import numpy
import numpy as np

arr1 = np.array([4, 4, 9, 16, 35, 1, 4, 2, 3, 2, 7, 6, 5, 7, 8, 10, 1, 3, 77])

unique, counts = np.unique(arr1, return_counts=True)

arr = np.asarray((unique, counts)).T

print(arr)


[[ 1  2]
 [ 2  2]
 [ 3  2]
 [ 4  3]
 [ 5  1]
 [ 6  1]
 [ 7  2]
 [ 8  1]
 [ 9  1]
 [10  1]
 [16  1]
 [35  1]
 [77  1]]
